stages:
  first_procedure:
    cmd: python src/firstprocedure.py
    deps:
    - data1/values.csv
    - src/firstprocedure.py
    # params:
    # - data_ingestion.test_size
    outs:
    - data1/first_procedure_output.csv
  second_procedure:
    cmd: python src/secondprocedure.py
    deps:
    - data1/first_procedure_output.csv
    - src/secondprocedure.py
    outs:
    - data1/second_procedure_output.csv
#   feature_engineering:
#     cmd: python src/feature_engineering.py
#     deps:
#     - data/interim
#     - src/feature_engineering.py
#     params:
#     - feature_engineering.max_features
#     outs:
#     - data/processed
#   model_building:
#     cmd: python src/model_building.py
#     deps:
#     - data/processed
#     - src/model_building.py
#     params:
#     - model_building.n_estimators
#     - model_building.random_state
#     outs:
#     - models/model.pkl
#   model_evaluation:
#     cmd: python src/model_evaluation.py
#     deps:
#     - models/model.pkl
#     - src/model_evaluation.py
#     metrics:
#     - reports/metrics.json
# params:
# - dvclive/params.yaml
# metrics:
# - dvclive/metrics.json
# plots:
# - dvclive/plots/metrics:
#     x: step
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
